ccflags-$(CONFIG_DEBUG_DRIVER) := -DDEBUG
ccflags-$(CONFIG_ASSISTED_SUPERUSER) += -Isecurity/selinux/include -Isecurity/selinux/ss -Isecurity/selinux

obj-$(CONFIG_ASSISTED_SUPERUSER) += superuser.o